services:
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 268435456
          mode: 0700
    mem_limit: 512m
